### ISSUE TITLE
Inaccurate fee estimation

### ISSUE THREAD

**Issue by Neurone** [hiero-ledger/hiero-sdk-js#2848]
Cross linking [this issue here,](https://github.com/hashgraph/hedera-services/issues/4854) it seems still not clear if the issue is on the SDK or service side.

### Description

Executing `ContractCallQuery` with an automatic cost computation, the cost of the tx is sometimes miscalculated, causing the precheck to fail with `INSUFFICIENT_TX_FEE`:

```bash
transaction 0.0.11205@1675091501.521603607 failed precheck with status INSUFFICIENT_TX_FEE
```

This issue has been around for some years, and because of this the SDKs usually apply a multiplier (1.1) to work around that problem.

There are different open issues on this topic, and I think we should address it at the services level, not as a workaround in the SDKs.

We should already have the code that can do the correct computation, the precheck function. If that function can understand the fees are insufficient, the same should be possible for the estimate function.

Even though a precise estimation would not have been possible, as an extreme measure, I suggest increasing the result of the estimate function directly, lifting the burden to fix this to the several SDKs out there, and having at the same time a coherent response across the board.

### Steps to reproduce

Here is an example of a smart contract call where the cost estimation fails:

- Contract Identifier: 0.0.3350566
- Contract Source Code: https://github.com/hashgraph/guardian/blob/dbef5986469989da3b98dbd5a20ed2d3ef60344e/contracts/RetirementContract.sol
- Function Name: 'getPair
- First Parameter: 00000000000000000000000000000000002f9fde
- Second Parameter: 0000000000000000000000000000000000000000

I also deployed another new simple smart contract ([0.0.5133653](https://hashscan.io/testnet/contract/0.0.5133653)) you can test with this code:

```JavaScript
require("dotenv").config();
const { Client, ContractCallQuery } = require("@hashgraph/sdk");

async function main() {
  let client = Client.forTestnet();
  client.setOperator(process.env.OPERATOR_ID, process.env.OPERATOR_KEY);
  let contractId = "0.0.5133653";

  // query with explicit gas
  let query = await new ContractCallQuery()
    .setContractId(contractId)
    .setFunction("retrieve")
    .setGas(23474);

  let txResponse = await query.execute(client);
  console.log("Response with explicit gas:", txResponse.bytes);
  console.log();

  // query with computed gas
  query = await new ContractCallQuery()
    .setContractId(contractId)
    .setFunction("retrieve");

  txResponse = await query.execute(client); // ERROR: failed precheck with status INSUFFICIENT_GAS
  console.log("Response with estimated gas:", txResponse.bytes);
  process.exit(0);
}

main().catch((error) => {
  if (process.env.DEBUG) {
    console.log(error);
    process.exit(-1);
  }
});
```
Consider Hashscan is able to use the function without issue via the JSON RPC relay.

### Additional context

Tickets related to the same topic:

- https://github.com/hashgraph/hedera-sdk-js/issues/1425

### Hedera network

testnet

### Version

v0.34.1

### Operating system

None

**Comment by 0xivanov** [comment]
Hi @Neurone . We will investigate this. This is most likely an issue coming from services, but if we can narrow down the scenarios where it happens - that would be great.

**Comment by SimiHunjan** [comment]
Read through the consensus node issue and seems @Neurone is still waiting on a response from the team.

**Comment by ivaylonikolov7** [comment]
should be resolved via #3399 and `MirrorNode ContractEstimateQuery`.

**Comment by Neurone** [comment]
Hi guys, I just tried today (Hiero SDK v2.84) and the issue is not solved yet.
If you execute the example code you get the same error.

@ivaylonikolov7 @0xivanov Can you reopen this?

**Comment by Neurone** [comment]
I did some tests (below), and the issue is on the SDK side. As [mentioned here](https://github.com/hiero-ledger/hiero-consensus-node/issues/4854#issuecomment-2640178656), `ContractCallLocal` requires gas, that means the estimation of the gas still require setting gas. The SDK should use the mirror node to estimate the gas and not the `ContratCallLocal`.

In particular, to fix this, the SDK should:

1. When _gas is null, do not auto-call getCost(); instead first call MirrorNodeContractEstimateQuery to populate gas, then compute the payment from gas * exchange_rate.
2. Throw a clear "gas must be set" error on execute() if _gas is null, instead of letting getCost() fail (for any reason, i.e. the mirror node is not available, etc.)

Workaround for now for developers: always call `setGas()` on `ContractCallQuery`, using `MirrorNodeContractEstimateQuery` to obtain the value (as shown in steps 3-4 below).

Side note: the mirror node estimation seems a bit pessimistic (`25136` estimated vs `23474` real consumption and estimation via consensus node), so I'll probably open another issue on the mirror node side to check this.

```sh
========================================================================
STEP 1  Reproduce: ContractCallQuery without setGas()
========================================================================
Failed during getCost() with: INSUFFICIENT_GAS
  Stack frame is CostQuery.execute → ContractCallQuery._mapStatusError
  i.e. the SDK's auto cost-query (COST_ANSWER) is what fails,
  not the user's actual call.

========================================================================
STEP 2  Probe consensus node: COST_ANSWER at various gas values
========================================================================
Sending contractCallLocalMethod with responseType=COST_ANSWER
and an explicit gas field. Per services_contract_call_local.proto:
  "the node SHALL always consume the entire amount of offered
   gas in determining the fee for this query, so accurate gas
   estimation is important."

  gas=         0  →  INSUFFICIENT_GAS
  gas=         1  →  INSUFFICIENT_GAS
  gas=     21000  →  INSUFFICIENT_GAS
  gas=     23474  →  cost=0.03478046 ℏ
  gas=     25000  →  cost=0.03633978 ℏ
  gas=     50000  →  cost=0.06188556 ℏ
  gas=    100000  →  cost=0.11297714 ℏ
  gas=   1000000  →  cost=1.03262548 ℏ

========================================================================
STEP 3  Mirror Node estimate (proper way to get gas)
========================================================================
Mirror Node returned gas estimate: 25136
  (POST <mirror>/api/v1/contracts/call with estimate=true)

========================================================================
STEP 4  Run ContractCallQuery using the mirror estimate
========================================================================
Result bytes: 0x000000000000000000000000000000000000000000000000000000000000002a

========================================================================
CONCLUSION
========================================================================

Reading services_contract_call_local.proto, the protocol for
contractCallLocalMethod is:

  - The 'gas' field is caller-supplied and required.
  - The node consumes the *entire* offered gas in computing the fee,
    so the cost is essentially  gas * tinybars-per-gas.
  - "Accurate gas estimation is important" -- the protocol explicitly
    delegates gas estimation to the caller (typically via a Mirror
    Node simulation).

What the SDK does in ContractCallQuery (Query._beforeExecute):

    if (this._queryPayment != null) cost = this._queryPayment
    else                            cost = await this.getCost(client)   // <--

getCost() builds a CostQuery wrapping the same ContractCallQuery, which
serialises ContractCallLocalQuery with whatever 'gas' the user set --
NULL if setGas() was not called. NULL int64 in protobuf is encoded as 0,
so the consensus node receives gas=0 and rejects with INSUFFICIENT_GAS.

Step 2 above confirms this empirically: the node returns a cost as soon
as gas >= the EVM intrinsic floor and rejects below that.

==> The consensus node is behaving per spec (issue #4854 is not a node
    bug; gas=0 is genuinely insufficient and the protocol does not ask
    the node to *infer* the gas needed).

==> The SDK is wrong (issue #2848): for ContractCallQuery, getCost()
    cannot work without a user-supplied gas, because the cost is
    *defined* in terms of the gas the user is going to offer. The fix
    in the SDK should be both the following:

      a) When _gas is null, do not auto-call getCost(); instead first
         call MirrorNodeContractEstimateQuery to populate gas, then
         compute the payment from gas * exchange_rate.
      b) Throw a clear "gas must be set" error on execute() if _gas is null, instead
         of letting getCost() fail (for any reason, i.e. the mirror node is not available, etc.)
```

This is the script:

```javascript
// Diagnostic script for hiero-sdk-js #2848 / hiero-consensus-node #4854
//
// What it does:
//  1. Reproduces the failure (ContractCallQuery with no setGas()).
//  2. Drives the consensus node directly by sending a contractCallLocal
//     query in COST_ANSWER mode with explicit gas values (0, 1, 21000, 25000,
//     50000, 100k, 1M). We do this by subclassing ContractCallQuery and
//     overriding _onMakeRequest so that getCost() (which reuses _onMakeRequest
//     under a CostQuery wrapper) sends our chosen gas. This shows what the
//     consensus node actually responds for each gas value.
//  3. Calls the Mirror Node /api/v1/contracts/call?estimate=true endpoint
//     (via MirrorNodeContractEstimateQuery) to get the real estimate.
//  4. Runs the actual ContractCallQuery using the mirror estimate as gas.
//
// Run:  DEBUG=true node diagnose-2848.js
require("dotenv").config();

const {
    Client,
    ContractId,
    ContractCallQuery,
    MirrorNodeContractEstimateQuery,
} = require("@hiero-ledger/sdk");

const CONTRACT_ID = "0.0.5133653";
const FUNCTION = "retrieve";

const SECTION = (title) => {
    console.log("\n" + "=".repeat(72));
    console.log(title);
    console.log("=".repeat(72));
};

// Subclass that lets us override the `gas` field that the SDK serialises into
// the ContractCallLocalQuery. The SDK's CostQuery wraps our query and reuses
// our _onMakeRequest, so this is enough to drive COST_ANSWER with arbitrary
// gas values.
class CustomGasCallQuery extends ContractCallQuery {
    setRawGas(gas) {
        this._rawGas = gas;
        return this;
    }
    _onMakeRequest(header) {
        return {
            contractCallLocal: {
                header,
                contractID:
                    this._contractId != null
                        ? this._contractId._toProtobuf()
                        : null,
                gas: this._rawGas,
                functionParameters: this._functionParameters,
                maxResultSize: this._maxResultSize,
                senderId:
                    this._senderAccountId != null
                        ? this._senderAccountId._toProtobuf()
                        : null,
            },
        };
    }
}

async function probeNodeCost(client, gas) {
    const q = new CustomGasCallQuery()
        .setContractId(ContractId.fromString(CONTRACT_ID))
        .setFunction(FUNCTION)
        .setRawGas(gas);
    try {
        const cost = await q.getCost(client);
        return { ok: true, cost };
    } catch (e) {
        return {
            ok: false,
            status: e.status ? e.status.toString() : e.message,
        };
    }
}

async function main() {
    const client = Client.forTestnet();
    client.setOperator(process.env.OPERATOR_ID, process.env.OPERATOR_KEY);

    // ---------------------------------------------------------------
    SECTION("STEP 1  Reproduce: ContractCallQuery without setGas()");
    // ---------------------------------------------------------------
    try {
        const q = new ContractCallQuery()
            .setContractId(ContractId.fromString(CONTRACT_ID))
            .setFunction(FUNCTION);
        await q.execute(client);
        console.log("UNEXPECTED: succeeded");
    } catch (e) {
        console.log(`Failed during getCost() with: ${e.status?.toString()}`);
        console.log(
            "  Stack frame is CostQuery.execute → ContractCallQuery._mapStatusError",
        );
        console.log(
            "  i.e. the SDK's auto cost-query (COST_ANSWER) is what fails,",
        );
        console.log("  not the user's actual call.");
    }

    // ---------------------------------------------------------------
    SECTION("STEP 2  Probe consensus node: COST_ANSWER at various gas values");
    // ---------------------------------------------------------------
    console.log("Sending contractCallLocalMethod with responseType=COST_ANSWER");
    console.log("and an explicit gas field. Per services_contract_call_local.proto:");
    console.log('  "the node SHALL always consume the entire amount of offered');
    console.log('   gas in determining the fee for this query, so accurate gas');
    console.log('   estimation is important."\n');

    const gasValues = [0, 1, 21_000, 23_474, 25_000, 50_000, 100_000, 1_000_000];
    for (const gas of gasValues) {
        const r = await probeNodeCost(client, gas);
        const label = `  gas=${String(gas).padStart(10)}`;
        if (r.ok) {
            console.log(`${label}  →  cost=${r.cost.toString()}`);
        } else {
            console.log(`${label}  →  ${r.status}`);
        }
    }

    // ---------------------------------------------------------------
    SECTION("STEP 3  Mirror Node estimate (proper way to get gas)");
    // ---------------------------------------------------------------
    let mirrorGas;
    try {
        mirrorGas = await new MirrorNodeContractEstimateQuery()
            .setContractId(ContractId.fromString(CONTRACT_ID))
            .setFunction(FUNCTION)
            .execute(client);
        console.log(`Mirror Node returned gas estimate: ${mirrorGas}`);
        console.log(
            "  (POST <mirror>/api/v1/contracts/call with estimate=true)",
        );
    } catch (e) {
        console.log(`Mirror estimate failed: ${e.message}`);
    }

    // ---------------------------------------------------------------
    SECTION("STEP 4  Run ContractCallQuery using the mirror estimate");
    // ---------------------------------------------------------------
    if (mirrorGas) {
        const result = await new ContractCallQuery()
            .setContractId(ContractId.fromString(CONTRACT_ID))
            .setFunction(FUNCTION)
            .setGas(mirrorGas)
            .execute(client);
        console.log(
            "Result bytes: 0x" + Buffer.from(result.bytes).toString("hex"),
        );
    }

    // ---------------------------------------------------------------
    SECTION("CONCLUSION");
    // ---------------------------------------------------------------
    console.log(`
Reading services_contract_call_local.proto, the protocol for
contractCallLocalMethod is:

  - The 'gas' field is caller-supplied and required.
  - The node consumes the *entire* offered gas in computing the fee,
    so the cost is essentially  gas * tinybars-per-gas.
  - "Accurate gas estimation is important" -- the protocol explicitly
    delegates gas estimation to the caller (typically via a Mirror
    Node simulation).

What the SDK does in ContractCallQuery (Query._beforeExecute):

    if (this._queryPayment != null) cost = this._queryPayment
    else                            cost = await this.getCost(client)   // <--

getCost() builds a CostQuery wrapping the same ContractCallQuery, which
serialises ContractCallLocalQuery with whatever 'gas' the user set --
NULL if setGas() was not called. NULL int64 in protobuf is encoded as 0,
so the consensus node receives gas=0 and rejects with INSUFFICIENT_GAS.

Step 2 above confirms this empirically: the node returns a cost as soon
as gas >= the EVM intrinsic floor and rejects below that.

==> The consensus node is behaving per spec (issue #4854 is not a node
    bug; gas=0 is genuinely insufficient and the protocol does not ask
    the node to *infer* the gas needed).

==> The SDK is wrong (issue #2848): for ContractCallQuery, getCost()
    cannot work without a user-supplied gas, because the cost is
    *defined* in terms of the gas the user is going to offer. The fix
    in the SDK should be both the following:

      a) When _gas is null, do not auto-call getCost(); instead first
         call MirrorNodeContractEstimateQuery to populate gas, then
         compute the payment from gas * exchange_rate.
      b) Throw a clear "gas must be set" error on execute() if _gas is null, instead
         of letting getCost() fail (for any reason, i.e. the mirror node is not available, etc.)
`);

    process.exit(0);
}

main().catch((error) => {
    if (process.env.DEBUG) {
        console.log(error);
        process.exit(-1);
    }
    process.exit(1);
});
```
